version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: white-board-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
